### ISSUE TITLE
協成 ERP 備標作業第一版測試後系統問題

### ISSUE THREAD

**Issue by jill1234** [m8508/topmeperp_v1#4]
1. 登入部分: 帳號密碼輸入後若帳號密碼無誤但無權限之角色,並無轉至相應的畫面
2.工率上傳成功後之頁面應加入共有多少筆資料於此頁面中
3.圖算數量修改應增加修改成功與否之訊息
4.專案修改部分: 因CREATED_ID與建立日沒寫入修改欄位中,所以修改完成按下"儲存"後, 這2個欄位的資料會被蓋掉變成NULL

**Comment by m8508** [comment]
帳號登入功能 若無權限已經調整
其餘功能Jill  已經調整
