### ISSUE TITLE
erp系統第二次測試錯誤內容說明

### ISSUE THREAD

**Issue by jill1234** [m8508/topmeperp_v1#6]
1. 新增詢價單功能之存放路徑錯誤: 應該是先到 form_id folder 再到 Quotes folder
2. 廠商報價單上傳時只能由"詢價單管理"路徑進入時才能成功上傳, 若是先帶入project_id 再上傳, 
    要帶入 project_id 的地方會帶入FileUpload 這個值, 而非進入FileUpload 這個action method, 
   故不能成功上傳
3. 目前由上傳方式匯入廠商報價單是新增一張全新的報價單而非更新原廠商報價單內容
4. 上傳廠商報價單只需更新"單價"即可
5. 比價頁面的廠報價總額不正確, 總額公式應為sum(各品項單價*數量)
6. 上傳圖算數量之頁面其專案編號欄位需設為不可編輯
7. 已將taskasiign 的task_type 資料型別由varbinary 改為varchar(50)

**Comment by m8508** [comment]
新增詢價單功能之存放路徑錯誤: 應該是先到 form_id folder 再到 Quotes folder
上傳圖算數量之頁面其專案編號欄位需設為不可編
